# gemfile.gems generated gem export file. Note that any env variable settings will be missing. Append these after using a ';' field separator
ruby "2.2.2"
gem "activemodel", "~> 5.0.0.1"
gem "activesupport", "~> 5.0.0.1"
gem "bigdecimal", "~> 1.2.6"
gem "bson", "~> 4.1.1"
gem "bundler", "~> 1.13.6"
gem "byebug", "~> 9.0.6"
gem "concurrent-ruby", "~> 1.0.2"
gem "i18n", "~> 0.7.0"
gem "io-console", "~> 0.4.3"
gem "json", "~> 1.8.1"
gem "minitest", "~> 5.9.1"
gem "mongo", "~> 2.3.1"
gem "mongoid", "~> 6.0.2"
gem "psych", "~> 2.0.8"
gem "rake", "~> 10.4.2"
gem "rdoc", "~> 4.2.0"
gem "thread_safe", "~> 0.3.5"
gem "tzinfo", "~> 1.2.2"
